### ISSUE TITLE
Remove packages

### ISSUE THREAD

**Issue by LukeShortCloud** [winesapOS/archupgrade-go#7]
A lot of times in winesapOS upgrades, a package needs to be replaced with another.

For example, most recently, we had to replace the older `steamtinkerlaunch` package with the newer and recommended `steamtinkerlaunch-git` package. See: https://github.com/winesapOS/winesapOS/issues/1009

Another scenario / use-case is that `fatx` prevents upgrades due to a GLIBC version dependency. Removing and then reinstalling the package fixes it.

Perhaps this can be part of the spec as where `packages_remove` runs before `packages`.

```
packages_remove:
  - name: fatx
  - name: steamtinkerlaunch
packages:
  - name: fatx
  - name: steamtinkerlaunch-git
```
